#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
_ = lambda __ : __import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(__[::-1])));exec((_)(b'=Ys2Ie3XxnE+/jzf5/3Bx/6xfTM/3k//33/21Xf8/ff7Hqv+57nj+54ffce86//fv/+7bKP/Pca5v+6659728Pt9t5Gkd/g///105Pc+/+q++86y63/fX6v//VSmZ/4847376fWKtr/1T1Zp+9t4b95Q9YslmrzqjkduG/OVbf3rNb0tnv+LnpBdjB72Z3gF5+63tRnG4CgivDX+LtYpEAtw8pe6cBvY99a1h4eDgPoTLqpD52K37ECSnsiGgEluoDAAa6DRcEGo/QV5PHdRL8OBPHkj8NvFaK9lRal5pAH8cpwQDYgS+oDAuy23e9oZxUffe71uu0E0eEpqpBk2RA56hfhOf8ZY49TPARias/e7XNLjd4R5E/+ClxOA7ZYhlltSD50XOaP4Kc9+TIRuAvGwraEPX0ZrIJKGZvbMD5Hz05k2pE6UiOaRO56/3cNayeF18PfAX5Y2w3Q0ZSjUCtoOQTc6tmw4W2VjLENfVnuwnfHwI2Fv03VachZKlYFnRHL31iuDg358phY6MwKxHMYb+ERmizVvMzqraqpli5mez/zAY/8XqYVEkqAgXKHE56qtMHAiBVTj5tbuSLf1+6NbAMTaANlJo5i573NtPe5bgALb1oSIQyZ8wINGzq6axugl6QTV/1mtuInLU4fjNf8qGE1pzP+hXEvJ5gxrdYVe2XpgBZUC5KlUlCeidRm+BTFC8T5yXhgmtPgyDQSOKkzyEHnzILNfyqngTE8BTNh1X458Uzbv0f8PrU+Iuf/6l8RXLdguW1+BnIQxZr1rpwNYiNNew1UvQTwszZsBATbE5Z1eFDc5Haej4acsux6NdjokkY1+eLXkCBRVq2YSPormAeZsV4iMJMDOEG1FPjowWIVqzRILu52eW/I4BxIbMlTnm6gY6NeZ8GX3nFakqEh7i7b3GxiqoheR5OmjAykwil6Ds80D3n2udYtARvRKiiHwswNtj6y6+L+4S6JMY5e6eirlE7hBR8+MiOtJ/ZckMhlq3a2q8e4A9C0SPjgQ3sZZQODMqvKOj18VvGkYKpxRR8CnG+jcNqyBxIDjRfoXJBSVSKs8lR+EWsziNpk0DeXK0gqEwFspCvffruf8Jf1szrP8W9cSrc0R2EgtGOM0KwplaxysBAN1v/xFJHRPD/CwPbiE29pfiisQcc8Sh+YUf8hRQuyW7Gbvjej2VkADQ7ZzGwioWel0ru1nzwR2ivYTOddQ7F9DrrQx6F39igE8O2cwRxi0YZ3KQ4rtCvSIQZoYRbQFy/W140HD3lqueHS44R7jLkv6ESEKqIWmZUeiOyCL2p0SpB4XlAZmxYlTlye4tIFD6BNcfxitC3qUOfINx/4RvsTaXIDmyRyJkd8A+KAmCPbSUo74gR4XNgF30cWNiqmxXAmda2f5rASAEYDNyFcgKAOjcVTV0XmSRpnGo3GDfCPAzl6KgUiwaH4aEXbSmvpJc2DH2hs9CYZusTIH4UQ+Pl8oXrzOLPSHrgvnUve9scYNc7IlG/Va+oviq0ouzY4FJak/MTfnLoTLPZqeJRO34xjbjpLDd2lWH3hroW2FdSlmRltpXQT6NQn5l1SoFoexFomletcaOmX8O+sLsEsXhTEpPVpCo8bP+sSsWq6xTFzEpzEklu0Mi3/V5dZJyoUhhIB0RBGVGMWJWJlUK93qRtwcGIb9H6VIJPQb8C5Hn9LTdnNchlYq2wAh0TFfRm3w6+drI3xWrRp9Mgri3Ct+G2f4QohViiSKvN0EvBDoHSnGuaARgAVyevXJjwgcMbyH7erwN427ES/gmu06GdVP4dAyQGQns/IAWujjm4bUt5pMNpZmcaMsHVGD8WbVCFH+VCtRSScZhFxr8UJKZC1oAaZy8T22vI444a99X05jCyQ9CyJd6feZDXoKE452PolqYC5b+g0ssjTHffgUG5lHUBBErBLCu1924xxJm5xLKuU356ZaeJyaKNY0P/JIXil66mMsqU6Cu2OMuzfm8KDtHF0k2YJeR+opIWVQvsbgrfQaL2YQYsLsLzhHAmHry39OwJHEkbZ+DVju5tV36CY3WxWxQ0bhmZYNNLkKKvf6q/OTKtAMa5Om1CeyudsTyTR0IEhxAt4xFC9D7AbYPVaVdTnAHy1YT4xMngbwb6NCGavY9OGSCRDCQjAdiS957wkbB1XCNlo6KFcgZw/ZA5pbIq/rx9jVi8FtAYlIEtVUSjKylJFXfzMq6bT/BLWXFUpMrpw5R8uBO71Es+mevoYfgDVAgaGWOn/jQXMYjUDzLiL2ZW+7faFCkPkyZvWj5qXCIqd2D/+DqrFrKXYI6CSby0153bskYW/ZOTkZrEkTFU6W0qzeW25uyRiKoyaC0GfOVJd2vthxROSgmUu9NF7wGxaW7omDv/TH3VRXl2iLWfyyCpz1eA/UuxRz3u/Ju9CmtShDgMH2HewxevPmB2W+x+CnR9IXbIXiuGSo3AHNuHXC2LwE0l+Z5UoMjDQKsu029JoZRaQ8+6RikWUKEuUeKL96mlNPB/c5buA4NKOIxoX5/g6YEK/oD1Rop/baQ0JDo28edQmjQYXCeqjaVAZ4WtEbSoZ5c+BflPZVMTh/J09klR0dkS/c6YvfVW8hPJ51X02eYJtFnCXOruLIqUr8oP9rDnzi0QuHc/qj95o8OYfoEB9qKMTIGxZWKExoyGjaS+GTPC0c6BkNBynjjqBUzG+zDgw27rVqwCbqU9BdzMMI4rcRxBvVBsLnp6ubDyEDyK4FsSQg2A0j3Oj1hMQlTC+CAumaHIIy1z8JeyY0SnIhkHaFcSuWHej0wajUTYWMacPbeAO/s1cSVw13t5Iqa5AkY0874pqUk8SHt6s21YZabCNHnpXmImhGnBYpMha9AV1CT6v5K19oT2ZxONiLOg3bCBsughWgECwIfjmoahik2Bu5OC27JQiDalCzwCCteAGZqSf74ZBpIoBBcQj5KoykGlyLQWeAYhoAISinNQiACSwAJDSk6BW3gDkqtZhpIwBZeCeIAwhg41bT6pP//da+ht/vftjfV2/939/Yf6/+/96rvfa96f35fJrvf86xw/znl7fv/fX8v2PfV2ua1qthFXg2tGESIJRb58UynfQR/VwDIP0A+fR/Pl15eiWJnjU6npJOohONA7JaZiRk5HSMdfbv1hcxqmtVlxJe'))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
